# Generated by Django 6.0.4 on 2026-05-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_actual', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'inventario_inventario',
            },
        ),
    ]
