# Generated by Django 6.0.4 on 2026-06-18 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('unidadmedida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_actual', models.IntegerField(default=0)),
                ('accion', models.CharField(blank=True, default='', max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='productos.producto')),
                ('tipo_unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidadmedida.unidadmedida')),
            ],
            options={
                'db_table': 'inventario_inventario',
            },
        ),
    ]
