# Generated by Django 6.0.4 on 2026-05-19 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('productos', '0007_producto_presentacion'),
        ('unidadmedida', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='id_inven',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='tipoUnidad',
        ),
        migrations.AddField(
            model_name='inventario',
            name='tipo_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidadmedida.unidadmedida'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='stock_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='inventario',
            table='inventario_inventario',
        ),
    ]
