# Generated by Django 6.0.4 on 2026-05-19 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('productos', '0001_initial'),
        ('unidadmedida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='producto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='tipo_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidadmedida.unidadmedida'),
        ),
    ]
