# Generated by Django 6.0.4 on 2026-05-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidadmedida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmedida',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
