# Generated by Django 6.0.4 on 2026-06-18 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('metodopago', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(db_column='IdVenta', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='Fecha')),
                ('total', models.DecimalField(db_column='Total', decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(db_column='IdCliente', on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='clientes.cliente')),
                ('metodo_pago', models.ForeignKey(db_column='IdMetPago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='metodopago.metodopago')),
            ],
            options={
                'db_table': 'VENTAS',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle', models.AutoField(db_column='IdDetalle', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
                ('subtotal', models.DecimalField(db_column='Subtotal', decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(db_column='IdProducto', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_venta', to='productos.producto')),
                ('venta', models.ForeignKey(db_column='IdVenta', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'db_table': 'DETALLE_VENTA',
            },
        ),
    ]
