# Generated by Django 6.0.4 on 2026-05-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_met_pago', models.AutoField(primary_key=True, serialize=False)),
                ('tipoPago', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'metodo_pago',
            },
        ),
    ]
