# Generated by Django 6.0.4 on 2026-05-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cambiar_password',
            field=models.BooleanField(default=True),
        ),
    ]
