# Generated by Django 6.0.4 on 2026-06-18 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidadmedida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='unidadmedida.unidadmedida')),
            ],
        ),
    ]
