# Generated by Django 6.0.4 on 2026-05-19 08:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('presentacion', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codProducto', models.CharField(blank=True, max_length=45, null=True, unique=True, verbose_name='Código de Producto')),
                ('nomProducto', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('precioCompra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('precioVenta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('stockMinimo', models.IntegerField(default=0)),
                ('tipoUnidad', models.CharField(default='unidad', max_length=100)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria')),
                ('presentacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presentacion.presentacion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'productos',
                'ordering': ['nomProducto'],
            },
        ),
    ]
