# Generated by Django 6.0.4 on 2026-05-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tipoUnidad',
        ),
    ]
