# Generated by Django 6.0.4 on 2026-05-19 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentacion', '0001_initial'),
        ('productos', '0006_remove_producto_stockactual'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='presentacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presentacion.presentacion'),
        ),
    ]
