# Generated by Django 6.0.4 on 2026-05-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('razonSocial', models.CharField(blank=True, max_length=150, null=True)),
                ('carnet', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('zona', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('numeroCasa', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
