# Generated by Django 6.0.4 on 2026-06-18 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(db_column='IdCompre', primary_key=True, serialize=False)),
                ('total', models.DecimalField(db_column='Total', decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('estado', models.BooleanField(db_column='Estado', default=True)),
                ('proveedor', models.ForeignKey(db_column='IdProv', on_delete=django.db.models.deletion.CASCADE, related_name='compras_realizadas', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'COMPRA',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detalle_compra', models.AutoField(db_column='IdDetalleCompra', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
                ('subtotal', models.DecimalField(db_column='Subtotal', decimal_places=2, editable=False, max_digits=10)),
                ('compra', models.ForeignKey(db_column='IdCompra', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.compra')),
                ('producto', models.ForeignKey(db_column='IdProducto', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_compra', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compras',
                'db_table': 'DETALLE_COMPRA',
            },
        ),
    ]
