# Generated by Django 6.0.4 on 2026-05-19 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_compra', to='inventario.inventario'),
        ),
    ]
